import { Chapter, TeamMember } from './types';

export const CHAPTERS: Chapter[] = [
  { id: 'chapter1', title: 'فصل ۱: خوش‌آمدگویی' },
  { id: 'chapter2', title: 'فصل ۲: ارزش‌ها و قول ما' },
  { id: 'chapter3', title: 'فصل ۳: تیم و نقش‌ها' },
  { id: 'chapter4', title: 'فصل ۴: فرهنگ و قوانین' },
  { id: 'chapter5', title: 'فصل ۵: هنر میزبانی' },
  { id: 'chapter6', title: 'فصل ۶: ایمنی و بهداشت' },
];

export const TEAM_MEMBERS: TeamMember[] = [
    { name: 'نیما جوان', description: 'کیمیاگر طعم و مزه و آفریدگار غذاهای خوشمزه. بانی سوال وجودی «کجویی؟» و کاشف فرمول طلایی «طعم = مزه + آروما»', imgSrc: '/pics/Javan.jpg', alt: 'عکس نیما جوان' },
    { name: 'امیر شوکت', description: 'مدیر همیشه‌درصحنه و مدبر همیشه‌حاضر. آماده‌ی خرید و مهیای تهیه‌ی ملزومات. عاشق عشق‌های پا(ر)ک و ابدی.', imgSrc: '/pics/Showcat.jpg', alt: 'عکس امیر شوکت' },
    { name: 'امید سامی', description: 'همان شف‌سامی تحت‌تعقیب! خندنده و خنداننده‌ی برتر توامان و سرشار از استعدادهای نهان.', imgSrc: '/pics/Omid.jpg', alt: 'عکس امید' },
    { name: 'مینا غریب‌پور', description: 'حافظ آرامش جمع و عاشق میوه و تره‌بار تازه. هادی امور به نحو احسن و استاد پخت هویج‌پلو.', imgSrc: '/pics/Mina.jpg', alt: 'عکس مینا' },
    { name: 'آرمین شوکت', description: 'قهرمان طلوع و آغازگر روز. کسی که قبل از همه در کافه حاضر است و هیچ مصدومیتی نمی‌تواند جلوی او را بگیرد.', imgSrc: '/pics/Armin.jpg', alt: 'عکس آرمین' },
    { name: 'آرشام صبوری', description: 'دوست‌دار زیبایی و عشق فیگور! پیش‌برنده‌ی کارها در سکوت به بهترین شکل ممکن.', imgSrc: '/pics/Arsham.jpg', alt: 'عکس آرشام' },
    { name: 'مسعود علی‌بیگی', description: 'حاضر در لحظات حساس و اندیشمند فلسفه‌ی «عمر دست خداست!». آرام، کاری و متأسفانه کمی بدشانس.', imgSrc: '/pics/Masoud.jpg', alt: 'عکس مسعود' },
    { name: 'دانیال معدل', description: 'آشپز هنرمند و هنرمند آشپز. کسی که غذا را نقاشی می‌کند حتی اگر هیچ‌چیز هم‌اندازه نباشد!', imgSrc: '/pics/Danial.jpg', alt: 'عکس دانیال' },
    { name: 'بهار امیری', description: 'معمار عشق به واسطه‌ی آشپزی. قدیمی‌ترین عضو تیم که زبان بیان علاقه و عشق‌اش، آشپزی برای دیگران است.', imgSrc: '/pics/Bahar.jpg', alt: 'عکس بهار' },
    { name: 'محمد رجاییان', description: 'کتاب دقت و متن بی‌حاشیه. ماشین سلیقه با کمترین میزان خطا. ناطق خاموش و عاشق بچه‌ها.', imgSrc: '/pics/Mamad.jpg', alt: 'عکس ممد' },
    { name: 'آرمان حیدری', description: 'ورزشکار با روحیه و بیزار از گفتن پدیده‌ی نامبارک «منم منم!»', imgSrc: '/pics/Arman.jpg', alt: 'عکس آرمان' },
    { name: 'امیر صادقی', description: 'عاشق چالش‌های جدید و آماده‌ی پیشرفت. خواهان یادگیری و خواستار چاقوی اورجینال!', imgSrc: '/pics/Amir.jpg', alt: 'عکس امیر' },
    { name: 'آرام حسینی', description: 'بی‌حاشیه مانند اسم‌اش با صدایی رسا برخلاف اسم‌اش.', imgSrc: '/pics/Aram.jpg', alt: 'عکس آرام' },
    { name: 'هدیه شیخی', description: 'شیفته‌ی شیفت‌های شلوغ، در آرزوی رزروهای زیاد. عاشق ورزش و موکا و دشمن شیشه‌شوی و الکل!', imgSrc: '/pics/Hedieh.jpg', alt: 'عکس هدیه' },
    { name: 'زهرا زارعی', description: 'متخصص فروش غذای روز با دو میل لایتناهی؛ میل به یادگیری و افزایش قیمت‌ها.', imgSrc: '/pics/Zahra.jpg', alt: 'عکس زهرا' },
    { name: 'علی رحیمی', description: 'مبادی آداب و منافی شبه‌علم. عاشق فکت‌های علمی، با هوشی که قطعا شما را به چالش می‌کشد.', imgSrc: '/pics/Ali.jpg', alt: 'عکس علی' },
    { name: 'ماجد حسینی', description: 'جدی و یکی از قدیمی‌ترین اعضای تیم، با تخصص رسمی در عرضه‌ی اجناس «فیک!» از بلاد غریب.', imgSrc: '/pics/Majed.JPG', alt: 'عکس ماجد' },
    { name: 'مریم خوش‌نظر', description: 'روانشناس سابق و آشپز لایق. از هر انگشت‌اش یک هنر می‌بارد اگر انگشتی بماند.', imgSrc: '/pics/Maryam.jpg', alt: 'عکس مریم' },
    { name: 'محمد مشکل‌گشا', description: 'حرفه‌ای در کار و آرام در ذات. شاگرد مکتب برزگ‌ترین آشپز ایران و دارای مدرک کف‌بینی از شهرک اُز.', imgSrc: '/pics/MoshkelGosha.jpg', alt: 'عکس محمد' },
    { name: 'حامد سروری', description: 'حکیم TDS و فقیه قهوه. هشدار: از دست زدن به گردن وی جدا خودداری نمایید!', imgSrc: '/pics/Sorouri.jpg', alt: 'عکس سروری' },
    { name: 'وحید یزدانی', description: 'سخت کوش و همیشه‌خوشحال. دوچرخه‌سوار با احساس و عاشق ویدیوکال‌های طولانی.', imgSrc: '/pics/Vahid.jpg', alt: 'عکس وحید' },
    { name: 'یاسی اصولی', description: 'غایبِ حاضر، موفق در محو شدن. کم‌رنگ‌ترین فرد کافه که غیبتش، حضور پررنگی دارد.', imgSrc: '/pics/Yasi.jpg', alt: 'عکس یاسی' },
    { name: 'عماد میرزاده', description: 'حسابداری دقیق با چشمانی ضعیف. عاشق کم کردن حقوق و پر کردن فضا از شایعه.', imgSrc: '/pics/Emad.jpg', alt: 'عکس عماد' },
    { name: 'امین رجائی', description: 'ترک‌خورده از فرط قدمت و خمیده از شدت پیری. موسیقیدان عنق با قوت غالب اسپرسو، مارگریتا و نوشابه.', imgSrc: '/pics/Raja.jpg', alt: 'عکس رجائی' },
    { name: 'سهند میرزاده', description: 'غریبِ توی غربت و متولی محبت! مونس پرسنل و نابودگر کبدهای شما.', imgSrc: '/pics/Sahand.jpg', alt: 'عکس سهند' },
    { name: 'حامد حدائق', description: 'عاشق پرسنل، قهوه و بادام هندی. ناهی خرید جدید وقتی که تند راه می‌رود، مشکل‌گشای امور و ریزبین وقتی که راه نمی‌رود.', imgSrc: '/pics/Hamed.jpg', alt: 'عکس حامد' },
    { name: 'سما ثامری پور', description: 'عضو جدید', imgSrc: 'https://placehold.co/128x128/C3A38A/4A3F35?text=?', alt: 'عکس سما ثامری پور' },
    { name: 'زهرا باقری', description: 'عضو جدید', imgSrc: 'https://placehold.co/128x128/C3A38A/4A3F35?text=?', alt: 'عکس زهرا باقری' },
    { name: 'نیکتا بیات', description: 'عضو جدید', imgSrc: 'https://placehold.co/128x128/C3A38A/4A3F35?text=?', alt: 'عکس نیکتا بیات' },
    { name: 'پریسا محمودی', description: 'عضو جدید', imgSrc: 'https://placehold.co/128x128/C3A38A/4A3F35?text=?', alt: 'عکس پریسا محمودی' },
    { name: 'کیمیا یگانه', description: 'عضو جدید', imgSrc: 'https://placehold.co/128x128/C3A38A/4A3F35?text=?', alt: 'عکس کیمیا یگانه' },
    { name: 'جواد نجیبی', description: 'عضو جدید', imgSrc: 'https://placehold.co/128x128/C3A38A/4A3F35?text=?', alt: 'عکس جواد نجیبی' },
    { name: 'غزل منصوری', description: 'عضو جدید', imgSrc: 'https://placehold.co/128x128/C3A38A/4A3F35?text=?', alt: 'عکس غزل منصوری' },
    { name: 'حسین ایزدی', description: 'عضو جدید', imgSrc: 'https://placehold.co/128x128/C3A38A/4A3F35?text=?', alt: 'عکس حسین ایزدی' },
    { name: 'سحر فتحی', description: 'عضو جدید', imgSrc: 'https://placehold.co/128x128/C3A38A/4A3F35?text=?', alt: 'عکس سحر فتحی' },
    { name: 'مژده یاقوتی', description: 'عضو جدید', imgSrc: 'https://placehold.co/128x128/C3A38A/4A3F35?text=?', alt: 'عکس مژده یاقوتی' },
  ];